GET http://localhost:5000/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzNzcwMTk5OCwianRpIjoiZWNlMzc2MjUtMTEzMi00NmJjLTg1OTctMDI2ZWFhMmU2M2Y2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNjM3NzAxOTk4LCJleHAiOjE2Mzc3MDI4OTh9.iE_Kr0BdfTyXzjBfu43qz-4V5jH3FG8V3J-dg4jCZwQ